#!/usr/bin/env python3

"""Diccionarios de traduccion de los addons cosechados en la sesion del 13-08-2026.

Los forks chinos tradujeron nombres, descripciones y mensajes, asi que sin esto los objetos
llegan al servidor en chino y los jugadores se quejan -- que es justo lo que paso.

Se traduce del chino y no del ingles original porque en varios sitios el fork no solo tradujo:
cambio el texto. Nexcavate es el caso claro, con toda una narrativa sobre una civilizacion del
Nether que pide ayuda, escrita por el fork.

IMPORTANTE: al aplicarlos hay que ir de la cadena MAS LARGA a la mas corta. Muchas son subcadena
de otra ("&5腐化" lo es de "&5腐化&4铃"), y en el orden natural la corta parte a la larga y deja
un resto en chino pegado a la traduccion.

Los codigos de color (&c, &7...) y los marcadores se conservan tal cual.
"""

NEXCAVATE = {
    # --- Narrativa: una civilizacion del Nether que pide ayuda para renacer ---
    "&7&o此文明重现其伟大的唯一方法是使用一种特殊的工具，但这种工具只能用他们无法获得的材料来制作":
        "&7&oLa única forma de devolverles su grandeza es una herramienta muy concreta, hecha con materiales que ellos nunca pudieron conseguir",
    "&7&o一些痕迹仍然存在于剩余结构的&e墙壁&7&o上，但对于物种来说是不可恢复的":
        "&7&oQuedan rastros en los &emuros&7&o de lo que sigue en pie, pero para su especie ya no hay vuelta atrás",
    "&7&o一个&e考古镐&7&o, 它可以提取猪灵堡垒周围方块中的古代零件":
        "&7&oUn &epico arqueológico&7&o, capaz de extraer piezas antiguas de los bloques que rodean las fortalezas piglin",
    "&9&o是啊，当然。自从那次大规模灭绝以来，只花了大概179000年。":
        "&9&oYa, claro. Solo han pasado unos 179.000 años desde la extinción.",
    "&d成功构建 &e研究台&d 你感觉到一股巨大的能量从下界深处散发出来":
        "&dHas construido la &emesa de investigación&d. Notas una energía enorme subiendo desde lo hondo del Nether",
    "&7&o在&kGreat Abcdefghi&7&o后它们变成了废墟":
        "&7&oTras el &kGreat Abcdefghi&7&o quedaron reducidas a ruinas",
    "&a您当前的研究已经完成！请打开Slimefun指南或研究站查看配方":
        "&a¡Tu investigación ha terminado! Abre la guía de Slimefun o la mesa de investigación para ver la receta",
    "&9&o当然了。我很高兴我们的文明在经历了几千年后还能继续存在。":
        "&9&oPor supuesto. Me alegra que nuestra civilización siga en pie después de milenios.",
    "&9&o他们重建了...我们的文明。那些是我们的建筑工吗?":
        "&9&oHan reconstruido... nuestra civilización. ¿Esos son nuestros constructores?",
    "&7&o请帮帮我们，我们需要你来重建我们曾经伟大的文明。":
        "&7&oAyúdanos, por favor. Te necesitamos para reconstruir la civilización que fuimos.",
    "&a&o看到了吗？我告诉过你会有人来救我们的！我就知道！":
        "&a&o¿Ves? ¡Te dije que alguien vendría a salvarnos! ¡Lo sabía!",
    "&7请在此位置放置一个物品架，并将物品放入其中进行组装 ":
        "&7Coloca aquí un soporte para objetos y mete dentro el objeto que quieras ensamblar ",
    "&d用于唤醒 &kasdfg hijklmn &d文明":
        "&dSirve para despertar a la civilización &kasdfg hijklmn",
    "&7&o这个物种，连同它所有的文明，都被从下界中抹去了":
        "&7&oEsta especie, y toda su civilización, fue borrada del Nether",
    "&7如图所示，将当前结构的所有物品层放置在当前世界中":
        "&7Coloca en el mundo todas las capas de la estructura tal y como se muestran",
    "&d你变得困惑&f&o什么? &r&d你在自言自语":
        "&dTe quedas desconcertado. &f&o¿Qué? &r&dHablas solo",
    "有关如何使用该命令的更多详细说明，请参见wiki":
        "Para más detalles sobre cómo usar el comando, consulta la wiki",
    "&d你还没来得及问任何问题，那个声音已经离开了":
        "&dAntes de que te dé tiempo a preguntar nada, la voz se ha ido",
    "&7&o我相信你已经见过我们的一些堡垒遗迹了":
        "&7&oSupongo que ya habrás visto alguna de nuestras fortalezas en ruinas",
    "&d令你惊讶的是，一个神秘的声音穿透了空气":
        "&dPara tu sorpresa, una voz misteriosa atraviesa el aire",
    "&a&o他们是怎么得到建造它的零件的?":
        "&a&o¿De dónde habrán sacado las piezas para construirlo?",
    "&7&o它们曾经是高度发达文明的家园。":
        "&7&oFueron el hogar de una civilización muy avanzada.",
    "&9&o他们一定是从另一个世界穿越而来":
        "&9&oTienen que haber venido de otro mundo",
    "&9&o什么？是谁把我从沉睡中唤醒？":
        "&9&o¿Qué? ¿Quién me ha despertado?",
    "&7物品架中的物品可在装配机中使用":
        "&7El objeto del soporte se puede usar en la ensambladora",
    "&7&o能够实现现在不可想象的事情":
        "&7&oCapaces de lograr cosas hoy impensables",
    "&7通电时，可无限将其施放至黑石中":
        "&7Con energía, lo proyecta sin límite sobre la piedra negra",
    "&7将组件的所有物品层放入组装机中":
        "&7Mete en la ensambladora todas las capas del componente",
    "&7&o我们被困在这里太久了...":
        "&7&oLlevamos atrapados aquí demasiado tiempo...",
    "&7装配小范围3x3x3内的方块":
        "&7Ensambla bloques en un radio pequeño de 3x3x3",
    "&a&o嗯，你还是应该感激 &e":
        "&a&oBueno, aun así deberías agradecérselo a &e",
    "未知的子命令！可用的子命令有: ":
        "¡Subcomando desconocido! Los disponibles son: ",
    "&7装配大范围4x4x4内的方块":
        "&7Ensambla bloques en un radio grande de 4x4x4",
    "&a&o等等...那是什么东西?":
        "&a&oEspera... ¿eso qué es?",
    "&7更快地从黑石中提取古代零件":
        "&7Extrae piezas antiguas de la piedra negra más rápido",
    "&7缓慢地从黑石中提取古代零件":
        "&7Extrae piezas antiguas de la piedra negra despacio",
    "&7任意组装机零件或磨制黑石砖":
        "&7Cualquier pieza de ensambladora o ladrillo de piedra negra pulida",
    "您只能以玩家的形式执行该指令":
        "Este comando solo puede usarlo un jugador",
    "您没有输入具有结构的有效物品":
        "No has indicado un objeto válido con estructura",
    "使用方法: /nexcavate validate <结构> [<方位>]":
        "Uso: /nexcavate validate <estructura> [<orientación>]",
    "&7请通过文明研究台查看配方": "&7Consulta la receta en la mesa de investigación",
    "&f并将物品放入架内进行组装": "&fy mete el objeto en el soporte para ensamblarlo",
    "&7必须放在下界的岩浆源上": "&7Debe colocarse sobre una fuente de lava del Nether",
    "&l&4当前无法查看配�!": "&l&4¡Ahora mismo no puedes ver la receta!",
    "&l&4当前无法查看配方!": "&l&4¡Ahora mismo no puedes ver la receta!",
    "&f在此放置一个&e物品架": "&fColoca aquí un &esoporte para objetos",
    "&d拥有远古下界文明的元素": "&dGuarda algo de la antigua civilización del Nether",
    "&7开始你的重建文明之旅": "&7Empieza tu viaje para reconstruir la civilización",
    "&d你放置了一个文明核心": "&dHas colocado un núcleo de civilización",
    "&7先进文明遗留下的产物": "&7Lo que dejó atrás una civilización avanzada",
    "装配机中的配方无法被识别": "No se reconoce la receta que hay en la ensambladora",
    "&7并激活它来组装该物品": "&7y actívalo para ensamblar el objeto",
    "提取古代零件的高级工具": "Herramienta avanzada para extraer piezas antiguas",
    "您没有使用该指令的权限": "No tienes permiso para usar este comando",
    "提取古代零件的基础工具": "Herramienta básica para extraer piezas antiguas",
    "&7允许你研究基础物品": "&7Te permite investigar los objetos básicos",
    "&7允许你研究高级物品": "&7Te permite investigar los objetos avanzados",
    "请将机器放置于下界中": "Coloca la máquina en el Nether",
    "请将机器放置在下界中": "Coloca la máquina en el Nether",
    "&c你已经在研究 &f": "&cYa estás investigando &f",
    "&7研究耗费: &f": "&7Coste de la investigación: &f",
    "&9&o上面写着&e": "&9&oDice así: &e",
    "&7研究进度: &7": "&7Progreso de la investigación: &7",
    " 交付足够的古代零件": " entrega suficientes piezas antiguas",
    "&7必须放置在下界中": "&7Debe colocarse en el Nether",
    "&e&l感谢游玩!": "&e&l¡Gracias por jugar!",
    "您没有看向固体方块": "No estás mirando a un bloque sólido",
    "&e文明研究实验室": "&eLaboratorio de investigación",
    "&d高级零件提取机": "&dExtractora de piezas avanzada",
    "&7古代文明的遗迹": "&7Restos de una civilización antigua",
    "&7时间: &f": "&7Tiempo: &f",
    "&8仅在下界工作": "&8Solo funciona en el Nether",
    "&7储存部分物品": "&7Almacena algunos objetos",
    "&7自动提取岩浆": "&7Extrae lava automáticamente",
    "&e古代升级核心": "&eNúcleo de mejora antiguo",
    "文明复兴研究进度": "Progreso de la investigación",
    "文明复兴 版本:": "Renacer de la civilización, versión:",
    "&a&o救了我们": "&a&onos ha salvado",
    "在此发现非法方块": "Se ha encontrado un bloque que no corresponde",
    "&d高级装配机": "&dEnsambladora avanzada",
    " (当前层数)": " (capa actual)",
    "&e零件提取机": "&eExtractora de piezas",
    "&e基础装配机": "&eEnsambladora básica",
    "&e文明研究台": "&eMesa de investigación",
    "&e黑石提取机": "&eExtractora de piedra negra",
    "灯笼/灵魂灯笼": "Farol o farol de almas",
    "&c您无法为 ": "&cNo puedes hacerlo para ",
    "&b文明核心": "&bNúcleo de civilización",
    "&e&l终章": "&e&lFinal",
    "&4&l锁定": "&4&lBloqueado",
    "&c考古钻头": "&cTaladro arqueológico",
    "&e古代零件": "&ePieza antigua",
    "&5文明复兴": "&5Renacer de la civilización",
    "&e考古镐": "&ePico arqueológico",
    "组装机零件": "Pieza de ensambladora",
    "&f物品架": "&fSoporte para objetos",
    "结构有效!": "¡La estructura es válida!",
    "古代零件": "Pieza antigua",
    "&5装配": "&5Ensamblar",
    "&f返回": "&fVolver",
    "&e层 ": "&eCapa ",
    "&5建造": "&5Construir",
    "结构预览": "Vista previa de la estructura",
    " 分钟": " minutos",
}

CRINGLE = {
    "§3§o主听到了汝的呼唤，以汝的名义敲响了大钟...":
        "§3§oEl Señor ha oído tu llamada y ha hecho sonar la gran campana en tu nombre...",
    "&5&kll&4狂妄之魂&5&kll": "&5&kll&4Alma soberbia&5&kll",
    "&6&kll&e净化之魂&6&kll": "&6&kll&eAlma purificada&6&kll",
    "&9&kll&b闪亮之魂&9&kll": "&9&kll&bAlma reluciente&9&kll",
    "&c必须在合适的召唤祭坛上使用": "&cDebe usarse sobre un altar de invocación adecuado",
    "&d祭坛 &3探查 - &e": "&dAltar &3· detección - &e",
    "&f便以神的名义带给人们救赎": "&fy trae la salvación en nombre de los dioses",
    "&f给予附近玩家增益Buff": "&fMejora a los jugadores cercanos",
    "&f他曾经是世上最邪恶的人": "&fFue el hombre más malvado del mundo",
    "&5你能听见他们的呼唤吗?": "&5¿Alcanzas a oír su llamada?",
    "&6使粘液看上去高贵了起来": "&6Hace que el limo parezca noble",
    "&c用于召唤各种Boss": "&cSirve para invocar a los distintos jefes",
    "&7当某人失足于黑暗中": "&7Cuando alguien se pierde en la oscuridad",
    "&c召唤祭坛的组成部分": "&cParte del altar de invocación",
    "&7便成为了古老的遗迹": "&7acaba convertido en una reliquia antigua",
    "&c一种多方块式的祭坛": "&cUn altar de varios bloques",
    "&5它的光是多么耀眼!": "&5¡Qué deslumbrante es su luz!",
    "&f削弱并显示附近玩家": "&fDebilita y revela a los jugadores cercanos",
    "&6灵魂中被玷污的碎片": "&6Un fragmento manchado de un alma",
    "&5但它是否真的可燃?": "&5¿Pero de verdad arde?",
    "&f迷惑并显示附近玩家": "&fConfunde y revela a los jugadores cercanos",
    "&7来自某些人的灵魂": "&7Procede del alma de alguien",
    "&5灵魂与你窃窃私语": "&5Las almas te susurran",
    "&7用于召唤混沌幽灵": "&7Sirve para invocar al espectro del caos",
    "&b也许是某种收藏品": "&bQuizá sea una pieza de coleccionista",
    "&7不影响敲钟人自身": "&7No afecta a quien toca la campana",
    "&6大钟为汝敲响了": "&6La gran campana ha sonado por ti",
    "&f现在它为了赎罪": "&fAhora busca redimirse",
    "&7逐渐地被人淡忘": "&7y poco a poco cae en el olvido",
    "&f鼓舞附近的玩家": "&fAnima a los jugadores cercanos",
    "&f并给予腐败效果": "&fy aplica el efecto de corrupción",
    "&a> 单击打开": "&a> Clic para abrir",
    "&5杀死失魂生物": "&5Mata criaturas sin alma",
    "&7混沌Boss": "&7Jefe del caos",
    "&c杀死腐败生物": "&cMata criaturas corruptas",
    "&5杀死神圣生物": "&5Mata criaturas sagradas",
    "&5杀死寒武生物": "&5Mata criaturas primigenias",
    "&6带给人间温暖": "&6Trae calor al mundo",
    "&5击杀混沌生物": "&5Mata criaturas del caos",
    "&f标记周围玩家": "&fMarca a los jugadores de alrededor",
    "&6最纯粹的灵魂": "&6El alma más pura",
    "&5腐化&4铃": "&5Campana &4corrupta",
    "&6摸上去很烫": "&6Quema al tocarla",
    "&b生物掉落物": "&bBotín de criatura",
    "&5混沌幽灵丹": "&5Esencia del espectro del caos",
    "&3皇家凝胶": "&3Gel real",
    "&6合成配方": "&6Receta",
    "&4破碎之魂": "&4Alma rota",
    "&b软硬兼施": "&bDuro y blando a la vez",
    "&4召唤祭坛": "&4Altar de invocación",
    "混沌的脚步声": "Pasos del caos",
    "&9硬化凝胶": "&9Gel endurecido",
    "&8暗夜之魂": "&8Alma de la noche",
    "&8隐匿之魂": "&8Alma oculta",
    "&a罪恶之钟": "&aCampana del pecado",
    "&4召唤基座": "&4Pedestal de invocación",
    "祖上的手稿": "Manuscrito de los ancestros",
    "古老的故事": "Una historia antigua",
    "&4幽魂钟": "&4Campana espectral",
    "&e腐化铃": "&eCampana corrupta",
    "&b寒武钟": "&bCampana primigenia",
    "知识的禁果": "El fruto prohibido del conocimiento",
    "灵魂的真理": "La verdad del alma",
    "遗忘在世间": "Olvidado en el mundo",
    "上帝的言语": "La palabra de los dioses",
    "&2罪恶": "&2Pecado",
    "&e神圣": "&eSagrado",
    "&5腐化": "&5Corrupción",
    "&e圣钟": "&eCampana sagrada",
    "&8古钟": "&8Campana antigua",
    "&b寒武": "&bPrimigenio",
    "&4混沌": "&4Caos",
    "&8古迹": "&8Reliquia",
    "猪灵": "Piglin",
}

BREWERY = {
    "&a探索酒精的美好世界...": "&aExplora el mundo de la destilación...",
    "火必须被楼梯包围": "El fuego tiene que estar rodeado de escaleras",
    "&e苏格兰威士忌": "&eWhisky escocés",
    "&e波旁威士忌酒": "&eBourbon",
    "需要火和其他热源": "Necesita fuego u otra fuente de calor",
    "&e爱尔兰威士忌": "&eWhisky irlandés",
    "&e苹果利口酒": "&eLicor de manzana",
    "&e苹果蜂蜜酒": "&eHidromiel de manzana",
    "&e绿色苦艾酒": "&eAbsenta verde",
    "&e鸡蛋利口酒": "&eLicor de huevo",
    "&e蘑菇伏特加": "&eVodka de setas",
    "&e白葡萄酒": "&eVino blanco",
    "&a蒸馏次数": "&aDestilaciones",
    "&e龙舌兰酒": "&eTequila",
    "&e杜松子酒": "&eGinebra",
    "&e红葡萄酒": "&eVino tinto",
    "&a烹饪时间": "&aTiempo de cocción",
    "&e苹果汁": "&eZumo de manzana",
    "&e伏特加": "&eVodka",
    "&e土豆汤": "&eSopa de patata",
    "&e苦艾酒": "&eAbsenta",
    "&e蜂蜜酒": "&eHidromiel",
    "&e朗姆酒": "&eRon",
    "&e黑啤酒": "&eCerveza negra",
    "金合欢木桶": "Barril de acacia",
    "酿酒桶: ": "Barril: ",
    "深色橡木桶": "Barril de roble oscuro",
    "&a桶类型": "&aTipo de barril",
    " 次数: ": " veces: ",
    "毒马铃薯": "Patata venenosa",
    "白桦木桶": "Barril de abedul",
    "&e啤酒": "&eCerveza",
    "发光浆果": "Bayas luminosas",
    "&e玉米": "&eMaíz",
    "&e麦酒": "&eCerveza de malta",
    "&e酵母": "&eLevadura",
    "将水灌满": "Llénalo de agua",
    "棕色蘑菇": "Seta marrón",
    "时间: ": "Tiempo: ",
    "&e咖啡": "&eCafé",
    "&e酿酒": "&eDestilar",
    "橡木桶": "Barril de roble",
    "桦木桶": "Barril de abedul",
    "蜂蜜瓶": "Botella de miel",
    " 分钟": " minutos",
    "任意桶": "Cualquier barril",
    "马铃薯": "Patata",
    "牛奶桶": "Cubo de leche",
    "仙人掌": "Cactus",
    "甜浆果": "Bayas dulces",
    "可可豆": "Grano de cacao",
    "红蘑菇": "Seta roja",
    "苹果": "Manzana",
    "小麦": "Trigo",
    " 年": " años",
    "玉米": "Maíz",
    "鸡蛋": "Huevo",
    "土豆": "Patata",
    "兰花": "Orquídea",
    "酵母": "Levadura",
    "糖": "Azúcar",
    "草": "Hierba",
}

SLIMYBEES = {
    "蜜蜂分析仪没有足够的能量来正常工作! ": "¡El analizador de abejas no tiene energía suficiente para funcionar! ",
    "&fShift左击: &7返回主菜单": "&fShift + clic izquierdo: &7volver al menú principal",
    "&e右击&7 获取绑定者的所有研究": "&eClic derecho&7 para heredar todas las investigaciones de quien lo vinculó",
    "&e右击&7 绑定你的蜜蜂研究": "&eClic derecho&7 para vincular tus investigaciones de abejas",
    "详情见蜜蜂册或附属 Wiki": "Más detalles en el catálogo de abejas o en la wiki",
    "&f将雄蜂和雌蜂放于输入槽内": "&fPon un zángano y una reina en las casillas de entrada",
    "&f左击: &7返回上一页": "&fClic izquierdo: &7página anterior",
    "&f一种蜂箱的重要组成部分": "&fUna pieza clave de la colmena",
    "&f给你的蜜蜂一个简单的家": "&fUn hogar sencillo para tus abejas",
    "请将任意蜂蜡放入离心机内": "Mete cualquier cera en la centrifugadora",
    "&f大幅度提升了生产效率": "&fAumenta mucho la producción",
    "请查阅蜜蜂图鉴或wiki": "Consulta el catálogo de abejas o la wiki",
    "&7电动离心机 &eII": "&7Centrifugadora eléctrica &eII",
    "&7电动离心机 &eI": "&7Centrifugadora eléctrica &eI",
    "&7寿命: &8&lx": "&7Longevidad: &8&lx",
    "&f养蜂人最信赖的工具": "&fLa herramienta de confianza del apicultor",
    "&7产量: &8&lx": "&7Producción: &8&lx",
    "&f该物品用于识别各种": "&fSirve para identificar las distintas",
    "&7放入离心机中获取": "&7Se obtiene metiéndolo en la centrifugadora",
    "&f便可自动进行繁殖": "&fy criará por su cuenta",
    "你发现了新物种 - ": "Has descubierto una especie nueva: ",
    "&f蜜蜂在蜂箱中工作": "&fLas abejas trabajan dentro de la colmena",
    "&f繁殖两种特定蜜蜂": "&fCruza dos abejas concretas",
    "&f可以组成蜂巢块": "&fSe puede montar en un bloque de panal",
    "&e任意雄蜂+雌蜂": "&eCualquier zángano + reina",
    "&f用于工业级蜂箱": "&fPara la colmena industrial",
    "以获取更多相关信息": "para más información",
    "&f一种顶级的蜂箱": "&fLa mejor colmena que hay",
    "&f需要手动操作!": "&f¡Hay que manejarla a mano!",
    "使用充电台为其充电": "Cárgalo en una estación de carga",
    "&f一种自动化蜂箱": "&fUna colmena automática",
    "&6&l工业蜂箱": "&6&lColmena industrial",
    "&6蜜蜂知识巨著": "&6Gran tratado de apicultura",
    "请参考wiki!": "¡Consulta la wiki!",
    "获取途径不止一种": "Se puede conseguir de varias formas",
    "&f所生产的产物": "&fLo que produce",
    "&7主人: &b": "&7Dueño: &b",
    "&f蜜蜂的特征": "&fRasgos de la abeja",
    "&6&l蜂王浆": "&6&lJalea real",
    "&6全自动蜂箱": "&6Colmena totalmente automática",
    "&7蜜蜂分析仪": "&7Analizador de abejas",
    "&f高级框架": "&fMarco avanzado",
    "&f这种蜂箱": "&fEsta colmena",
    "&4致命框架": "&4Marco letal",
    "&c蜜蜂产物": "&cProducto de la abeja",
    "&f在蜂箱中": "&fdentro de la colmena",
    "第一个发现了": "fue el primero en descubrir",
    "&4甜蜜框架": "&4Marco dulce",
    "&6蜜蜂后代": "&6Cría de abeja",
    "在世界中发现": "Se encuentra por el mundo",
    "&6&l花粉": "&6&lPolen",
    "&f基础框架": "&fMarco básico",
    "任意其他蜂蜡": "Cualquier otra cera",
    "&6蜜蜂产物": "&6Producto de la abeja",
    "&6基础蜂箱": "&6Colmena básica",
    "&6蜂巢外壳": "&6Carcasa de panal",
    "&6蜂巢板": "&6Placa de panal",
    "未发现物种": "Especie sin descubrir",
    "&7离心机": "&7Centrifugadora",
    "未发现几率": "Probabilidad sin descubrir",
    "&e蜂蜡油": "&eAceite de cera",
    "蜜蜂分析仪": "Analizador de abejas",
    "&f离心机": "&fCentrifugadora",
    "&f获取": "&fSe obtiene",
    "几率: ": "Probabilidad: ",
    "林业蜜蜂": "Abeja forestal",
    "&6蜂蜜": "&6Miel",
    "蜜蜂图鉴": "Catálogo de abejas",
    "任意蜂蜡": "Cualquier cera",
    "蜜蜂产出": "Produce",
    "&6蜂遗": "&6Herencia de la abeja",
    " 获取 ": " obtiene ",
    "&c繁殖": "&cCría",
    "<未知>": "<desconocido>",
    "蜜蜂册": "Catálogo de abejas",
    "&f甜": "&fDulce",
    "物种!": "¡especie!",
    "&e干": "&eSeco",
    "右击": "Clic derecho",
    "雄蜂": "Zángano",
    "左击": "Clic izquierdo",
    "蜂蜡": "Cera",
    "雌蜂": "Reina",
}

DRUGFUN = {
    "# 如果启用，“drugsFile”将被视为一个目录，其中 8 个文件将都被视为一种单独的药物":
        "# Si se activa, \"drugsFile\" se trata como una carpeta y cada uno de sus 8 ficheros como una sustancia distinta",
    "amount: 2 # 使用药物时，这是添加到计数器中的量（服用药物数量）":
        "amount: 2 # Cuánto suma al contador cada vez que se consume",
    "required: 5 # 如果计数器处于该阶段或更高阶段，则应用该效果":
        "required: 5 # A partir de este nivel del contador, se aplica el efecto",
    "# 如果材料以标签(#)开头，材料将被视为slimefun物品id":
        "# Si el material empieza por almohadilla (#), se trata como un id de objeto de Slimefun",
    "# 以下为药剂设置（服用过多药剂所获得的效果和药物过期设置）":
        "# Ajustes de las sustancias: efectos por abusar de ellas y caducidad",
    'id: "cocaine_research" # 研究 ID': 'id: "cocaine_research" # ID de la investigación',
    "# 粘液物品ID，你如果要添加新药品，你需要更改此ID":
        "# ID del objeto de Slimefun. Si añades una sustancia nueva, hay que cambiarlo",
    'type: "CONFUSION" # 药水效果类型': 'type: "CONFUSION" # Tipo de efecto de poción',
    "duration: 30 # 效果持续时间": "duration: 30 # Cuánto dura el efecto",
    "expire: 120 # 药物过期时间": "expire: 120 # Cuánto tarda en pasarse",
    "amplifier: 1 # 药水等级": "amplifier: 1 # Nivel del efecto",
    "# 储存文件后缀（慎改）": "# Extensión del fichero de datos (mejor no tocar)",
    "# 格式: 材料:数量": "# Formato: material:cantidad",
    "&7清除所有负面效果": "&7Quita todos los efectos negativos",
    "# 储存形式（慎改）": "# Formato de almacenamiento (mejor no tocar)",
    "&2医药科技": "&2Tecnología médica",
    "&b医用吗啡": "&bMorfina médica",
}

GLOBIA = {
    "&7一台集研磨、淘金、淘洗于一体的机器": "&7Muele, criba y lava, todo en una máquina",
    "&7[&6全球机器&7] &r": "&7[&6GlobiaMachines&7] &r",
    "&c你必须看向粘液科技方块": "&cTienes que estar mirando a un bloque de Slimefun",
    "&c没有可用的控制台指令": "&cNo hay comandos disponibles desde la consola",
    "&c这是一个多块机器!": "&c¡Esta máquina es de varios bloques!",
    "&c请指定密钥和数据": "&cIndica la clave y el dato",
    "&f任意圆石变种": "&fCualquier variante de piedra",
    "&a信息已添加": "&aInformación añadida",
    "&c指令未发现": "&cComando no encontrado",
    "&e当前版本:": "&eVersión actual:",
    "&c预算粉尘泵": "&cFabricadora de polvo económica",
    "&c无效指令": "&cComando no válido",
    "&6全球机器": "&6GlobiaMachines",
    "&7安山岩": "&7Andesita",
    "&7花岗岩": "&7Granito",
    "&7闪长岩": "&7Diorita",
    "&7圆石": "&7Piedra",
}

PRIVATESTORAGE = {
    "&r该箱子可以被任何有权限的玩家打开": "&rEste cofre puede abrirlo cualquier jugador con permiso",
    "&r只有你可以打开此箱子": "&rSolo tú puedes abrir este cofre",
    "&6金合欢木保险箱": "&6Caja fuerte de acacia",
    "&6深色橡木保险箱": "&6Caja fuerte de roble oscuro",
    "&a> 单击打开": "&a> Clic para abrir",
    "&6绿宝石保险箱": "&6Caja fuerte de esmeralda",
    "&7大小: &e": "&7Tamaño: &e",
    "&6白桦木保险箱": "&6Caja fuerte de abedul",
    "&6丛林木保险箱": "&6Caja fuerte de jungla",
    "&6金合欢木箱子": "&6Cofre de acacia",
    "&6黑曜石保险箱": "&6Caja fuerte de obsidiana",
    "&6深色橡木箱子": "&6Cofre de roble oscuro",
    "&6云杉木保险箱": "&6Caja fuerte de abeto",
    "&6云杉木箱子": "&6Cofre de abeto",
    "&6橡木保险箱": "&6Caja fuerte de roble",
    "&6白桦木箱子": "&6Cofre de abedul",
    "&6绿宝石箱子": "&6Cofre de esmeralda",
    "&6黑曜石箱子": "&6Cofre de obsidiana",
    "&6丛林木箱子": "&6Cofre de jungla",
    "&6钻石保险箱": "&6Caja fuerte de diamante",
    "&6钻石箱子": "&6Cofre de diamante",
    "&6金保险箱": "&6Caja fuerte de oro",
    "&6钢保险箱": "&6Caja fuerte de acero",
    "&7私人存储": "&7Almacenamiento privado",
    "&6铁保险箱": "&6Caja fuerte de hierro",
    "&6橡木箱子": "&6Cofre de roble",
    "&6钢箱子": "&6Cofre de acero",
    "&6金箱子": "&6Cofre de oro",
    "&6铁箱子": "&6Cofre de hierro",
    "改进存储": "Almacenamiento mejorado",
    "升级存储": "Mejora de almacenamiento",
    "魔法存储": "Almacenamiento mágico",
    "硬化存储": "Almacenamiento reforzado",
    "&b防爆": "&bA prueba de explosiones",
    "顶级存储": "Almacenamiento de primera",
}
